name = "multiplayer"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[build]
command = "yarn run build"
[build.upload]
format = "modules"
main = "index.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
]