name = "asdf-chat"
type = "javascript"
zone_id = "1cdd649f553403940cc21aff32aea316"
account_id = "342285476fa519e04a9db74787b46103"
route = "asdf.chat"
workers_dev = false



[build]
command = "yarn run build"
[build.upload]
format = "modules"
main = "index.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
]
